# Generated by Django 3.2.3 on 2021-06-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.TextField()),
                ('product_price', models.FloatField()),
                ('product_category', models.JSONField()),
                ('product_created', models.DateTimeField(auto_now_add=True)),
                ('product_updated', models.DateTimeField(auto_now=True)),
                ('product_owner', models.CharField(max_length=25)),
                ('product_stock', models.IntegerField()),
                ('product_rating', models.FloatField()),
                ('product_slugify', models.SlugField()),
            ],
        ),
    ]
