# Generated by Django 3.2.3 on 2021-06-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField(editable=False)),
                ('category', models.JSONField(blank=True)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField()),
                ('comments', models.TextField(default='Good Item!')),
                ('rate', models.FloatField()),
                ('rater', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(default='My Product'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_rating',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_slugify',
            field=models.SlugField(editable=False),
        ),
    ]
