# Generated by Django 3.2.3 on 2021-06-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210626_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='category',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_owner',
            field=models.CharField(editable=False, max_length=25),
        ),
    ]
