# Generated by Django 3.2.3 on 2021-06-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210626_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_media',
            field=models.JSONField(blank=True, default='null'),
            preserve_default=False,
        ),
    ]
