# Generated by Django 3.2.3 on 2021-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_product_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_media',
            field=models.JSONField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_rating',
            field=models.FloatField(blank=True, editable=False),
        ),
    ]
