# Generated by Django 3.2.3 on 2021-06-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_media',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
