# Generated by Django 3.2.3 on 2021-06-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210628_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_condition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
