# Generated by Django 3.2.3 on 2021-06-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210628_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.TextField(max_length=25),
        ),
    ]
