# Generated by Django 3.2.3 on 2021-06-29 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_rating_rater'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='given_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='comments',
            field=models.TextField(),
        ),
    ]
