# Generated by Django 3.2.3 on 2021-06-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_discount_minimum_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.IntegerField(),
        ),
    ]
