# Generated by Django 3.2.3 on 2021-07-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_rating_rater'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_sold_count',
            field=models.IntegerField(default=0),
        ),
    ]
